rethinkdb:
  image: dockerfile/rethinkdb
  ports:
   - "10301:8080"
   - "10302:28015"
   - "10303:29015"
server:
  build: .
  ports:
   - "10300:80"
  links:
   - "rethinkdb"
  environment:
    NODE_ENV: production
    PORT: 80
  command: npm start
